// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.4
// source: pb/crdt-broadcast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ECDSAPublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Curve string `protobuf:"bytes,1,opt,name=curve,proto3" json:"curve,omitempty"`
	X     []byte `protobuf:"bytes,2,opt,name=x,proto3" json:"x,omitempty"`
	Y     []byte `protobuf:"bytes,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *ECDSAPublicKey) Reset() {
	*x = ECDSAPublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_crdt_broadcast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECDSAPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSAPublicKey) ProtoMessage() {}

func (x *ECDSAPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_pb_crdt_broadcast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSAPublicKey.ProtoReflect.Descriptor instead.
func (*ECDSAPublicKey) Descriptor() ([]byte, []int) {
	return file_pb_crdt_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *ECDSAPublicKey) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

func (x *ECDSAPublicKey) GetX() []byte {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *ECDSAPublicKey) GetY() []byte {
	if x != nil {
		return x.Y
	}
	return nil
}

type CRDTBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message   []byte          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature []byte          `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Key       *ECDSAPublicKey `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CRDTBroadcast) Reset() {
	*x = CRDTBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_crdt_broadcast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CRDTBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRDTBroadcast) ProtoMessage() {}

func (x *CRDTBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_pb_crdt_broadcast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRDTBroadcast.ProtoReflect.Descriptor instead.
func (*CRDTBroadcast) Descriptor() ([]byte, []int) {
	return file_pb_crdt_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *CRDTBroadcast) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CRDTBroadcast) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CRDTBroadcast) GetKey() *ECDSAPublicKey {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_pb_crdt_broadcast_proto protoreflect.FileDescriptor

var file_pb_crdt_broadcast_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x62, 0x2f, 0x63, 0x72, 0x64, 0x74, 0x2d, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x0e, 0x45, 0x43, 0x44,
	0x53, 0x41, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x75, 0x72, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x75, 0x72, 0x76,
	0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x79, 0x22, 0x6a, 0x0a,
	0x0d, 0x43, 0x52, 0x44, 0x54, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_crdt_broadcast_proto_rawDescOnce sync.Once
	file_pb_crdt_broadcast_proto_rawDescData = file_pb_crdt_broadcast_proto_rawDesc
)

func file_pb_crdt_broadcast_proto_rawDescGZIP() []byte {
	file_pb_crdt_broadcast_proto_rawDescOnce.Do(func() {
		file_pb_crdt_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_crdt_broadcast_proto_rawDescData)
	})
	return file_pb_crdt_broadcast_proto_rawDescData
}

var file_pb_crdt_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_crdt_broadcast_proto_goTypes = []interface{}{
	(*ECDSAPublicKey)(nil), // 0: ECDSAPublicKey
	(*CRDTBroadcast)(nil),  // 1: CRDTBroadcast
}
var file_pb_crdt_broadcast_proto_depIdxs = []int32{
	0, // 0: CRDTBroadcast.key:type_name -> ECDSAPublicKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_crdt_broadcast_proto_init() }
func file_pb_crdt_broadcast_proto_init() {
	if File_pb_crdt_broadcast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_crdt_broadcast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECDSAPublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_crdt_broadcast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CRDTBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_crdt_broadcast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_crdt_broadcast_proto_goTypes,
		DependencyIndexes: file_pb_crdt_broadcast_proto_depIdxs,
		MessageInfos:      file_pb_crdt_broadcast_proto_msgTypes,
	}.Build()
	File_pb_crdt_broadcast_proto = out.File
	file_pb_crdt_broadcast_proto_rawDesc = nil
	file_pb_crdt_broadcast_proto_goTypes = nil
	file_pb_crdt_broadcast_proto_depIdxs = nil
}
